### ISSUE TITLE
can't get it to work with the latest buildout 3 pre-release

### ISSUE THREAD

**Issue by jugmac00** [gocept/batou_scm#11]
I tried the upcoming version 3 of buildout ... and got this error:

```
localhost: Scheduling component source ...
localhost > Supervisor > Buildout > File('work/supervisor/buildout.cfg') > Presence('buildout.cfg')
localhost > Supervisor > Buildout > File('work/supervisor/buildout.cfg') > Content('buildout.cfg')
  buildout.cfg ---
  buildout.cfg +++
  buildout.cfg @@ -0,0 +1,24 @@
  buildout.cfg +[buildout]
  buildout.cfg +parts = supervisor nagiosplugin
  buildout.cfg +newest = false
  buildout.cfg +versions = versions
  buildout.cfg +allow-picked-versions = false
  buildout.cfg +
  buildout.cfg +[versions]
  buildout.cfg +collective.recipe.supervisor = 1.0
  buildout.cfg +setuptools = 46.1.3
  buildout.cfg +meld3 = 2.0.1
  buildout.cfg +nagiosplugin = 1.3.2
  buildout.cfg +superlance = 1.0
  buildout.cfg +supervisor = 4.1
  buildout.cfg +zc.buildout = 2.13.3
  buildout.cfg +zc.recipe.egg = 2.0.7
  buildout.cfg +
  buildout.cfg +[nagiosplugin]
  buildout.cfg +recipe = zc.recipe.egg
  buildout.cfg +interpreter = py
  buildout.cfg +
  buildout.cfg +[supervisor]
  buildout.cfg +recipe = zc.recipe.egg
  buildout.cfg +eggs = supervisor
  buildout.cfg +    superlance
localhost > Supervisor > Buildout > VirtualEnv('3') > VirtualEnvPy
localhost > Supervisor > Buildout > VirtualEnv('3') > Package('setuptools==54.1.1')
localhost > Supervisor > Buildout > VirtualEnv('3') > Package('zc.buildout==3.0.0b1')
localhost > Supervisor > Buildout
ERROR: bin/buildout -t 3 -c "buildout.cfg"
Return code: 1
STDOUT

STDERR
Requires-Python support missing. 

Traceback (most recent call last):
  File "/home/jugmac00/Projects/bliss_deployment/work/supervisor/lib/python3.6/site-packages/zc/buildout/patches.py", line 50, in patch_PackageIndex
    from pip._internal.index.collector import HTMLPage
ModuleNotFoundError: No module named 'pip._internal'
Traceback (most recent call last):
  File "bin/buildout", line 7, in <module>
    from zc.buildout.buildout import main
  File "/home/jugmac00/Projects/bliss_deployment/work/supervisor/lib/python3.6/site-packages/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/home/jugmac00/Projects/bliss_deployment/work/supervisor/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 967, in <module>
    check_picked=False))
  File "/home/jugmac00/Projects/bliss_deployment/work/supervisor/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 964, in install
    return installer.install(specs, working_set)
  File "/home/jugmac00/Projects/bliss_deployment/work/supervisor/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 737, in install
    for dist in self._get_dist(req, ws):
  File "/home/jugmac00/Projects/bliss_deployment/work/supervisor/lib/python3.6/site-packages/zc/buildout/easy_install.py", line 557, in _get_dist
    % requirement)
zc.buildout.UserError: We don't have a distribution for wheel
and can't install one in offline (no-install) mode.
```

The buildout component is imported from `batou_scm`.

In order to rule out a problem on my machine or my setup, could you please setup a minimal example and try to use the latest buildout version 3? I have a hard time setup a minimal working example - I miss some documentation.

I both tried 
```
zc.buildout == 3.0.0b1
setuptools == 54.1.1
```
but also a lower version of setuptools with no success.

Thank you!

**Comment by jugmac00** [comment]
@icemac This is already an issue in the underlying `Buildout` component by FlyingCircus.

I will post an issue at their issue tracker and link it to here - it is up to you to close this here - not much you can do until it is fixed over there.

**Comment by icemac** [comment]
Closing this issue as it has to be fixed in batou, see https://github.com/flyingcircusio/batou/pull/263 over there.
